name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag scottjr632/go-supervise-client:latest
    - name: Start Docker image
      run: docker run --name client --rm -d scottjr632/go-supervise-client:latest
    - name: Test image
      run: docker run --network container:client appropriate/curl -s --retry 10 --retry-connrefused http://localhost:80
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: scottjr632/go-supervise-client/client
        username: ${{ secrets.GITHUB_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.GITHUB_DOCKER_REGISTRY_ACCESS_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        tag_names: true
      
